CREATE TABLE book (
id INT(10) AUTO_INCREMENT PRIMARY KEY,
author VARCHAR(255) NOT NULL,
launch_date DATETIME NOT NULL,
title VARCHAR(255) NOT NULL,
price DECIMAL(65,2) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;